global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'spring-actuator'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    basic_auth:
      username: 'admin'
      password: 'admin'
    static_configs:
      - targets: ['host.docker.internal:8080']
    scheme: http
    tls_config:
      insecure_skip_verify: true 